version: "3.8"

services:
  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    volumes:
      - ./Database:/db

  backend:
      build:
        context: ./Backend
        dockerfile: Dockerfile
      ports:
        - "${BACKEND_PORT}:${BACKEND_PORT}"
      environment:
        - BACKEND_PORT=${BACKEND_PORT}
        - MYSQL_HOST=database
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      volumes:
        - ./Backend:/app
        - /app/node_modules
      depends_on:
        database:
          condition: service_healthy
      restart: always
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - ./Frontend:/usr/share/nginx/html
    depends_on:
      - backend